### ISSUE TITLE
Dashboard revenue chart dates are backwards on the x-axis

### ISSUE THREAD

**Issue by TheStophe** [rosen-bridge/ui#3]
On the UI Dashboard, the new columns are showing up progressing left, while the new dates are progressing left, but going backwards in time - i.e. the dates are backwards on the x-axis.

Recommend having the new revenue bar charts and dates progressing to the right, with the newest date/column being the right most.

**Comment by mkermani144** [comment]
Fixed in https://github.com/rosen-bridge/ui/commit/3a37fb4ee20adc9846a456332ae90c3094f4f081.
