### ISSUE TITLE
in the status page for ergo watcher, hour shows 24 instead of 00 for midnight

### ISSUE THREAD

**Issue by 00lingy** [rosen-bridge/ui#5]
![Screenshot 2024-01-07 003850](https://github.com/rosen-bridge/ui/assets/8059510/50e182a4-8cf7-418a-9474-c53e4d6d345c)

seen in the above screenshot, the time is showing as 24:xx, when it is midnight, it should be showing "00:xx" instead.

**Comment by mkermani144** [comment]
Resolved in https://github.com/rosen-bridge/ui/commit/0c79405293dc44c908e37bb395457a24aced72c7.
